export const PEOPLE_GET_ALL = 'PEOPLE_GET_ALL';
export const PEOPLE_GET_ALL_SUCCESS = 'PEOPLE_GET_ALL_SUCCESS';
export const PEOPLE_GET_ALL_FAILED = 'PEOPLE_GET_ALL_FAILED';
export const PEOPLE_READ_BIO = 'PEOPLE_READ_BIO';
export const PEOPLE_SHOW_VIDEO = 'PEOPLE_SHOW_VIDEO';
export const PEOPLE_HIDE_VIDEO = 'PEOPLE_HIDE_VIDEO';
